# Generated by Django 5.0.6 on 2026-05-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='views',
            new_name='views_count',
        ),
        migrations.AddField(
            model_name='property',
            name='ai_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='engagement_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
