# Generated by Django 5.0.6 on 2026-05-21 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertylistingrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListingRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='requests/')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.propertylistingrequest')),
            ],
        ),
    ]
