# Generated by ChatGPT

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('RENT', 'For Rent'), ('SALE', 'For Sale'), ('RENT_TO_OWN', 'Rent To Own')], default='RENT', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_documents_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylistingrequest',
            name='property_type',
            field=models.CharField(choices=[('RENT', 'For Rent'), ('SALE', 'For Sale'), ('RENT_TO_OWN', 'Rent To Own')], default='RENT', max_length=20),
        ),
        migrations.CreateModel(
            name='PropertyOwnershipDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='ownership_documents/')),
                ('document_type', models.CharField(choices=[('TITLE_DEED', 'Title Deed'), ('TAX_DOCUMENT', 'Tax Document'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_documents', to='properties.property')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_ownership_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('RWF', 'Rwandan Franc'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', max_length=3)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('COUNTERED', 'Countered'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
                ('previous_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_offers', to='properties.offer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='properties.property')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
