# Generated by Django 5.0.6 on 2026-06-06 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_offer_and_ownership_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('UNDER_OFFER', 'Under Offer'), ('UNDER_REVIEW', 'Under Review'), ('UNDER_CONTRACT', 'Under Contract'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='properties__status_6427a0_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['views_count'], name='properties__views_c_030cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['latitude', 'longitude'], name='properties__latitud_6eb2b0_idx'),
        ),
    ]
