# Generated by Django 5.0.6 on 2026-05-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_customer_confirmed_booking_owner_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_request_reversal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='owner_request_reversal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_proof_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
