# Generated by ChatGPT

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_customer_request_reversal_and_more'),
        ('properties', '0008_offer_and_ownership_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='properties.offer'),
        ),
    ]
