# Generated by Django 5.0.6 on 2026-06-06 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('properties', '0009_alter_property_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='propertyinteraction',
            index=models.Index(fields=['property'], name='analytics_p_propert_ab78a9_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyinteraction',
            index=models.Index(fields=['interaction_type'], name='analytics_p_interac_65529a_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyinteraction',
            index=models.Index(fields=['timestamp'], name='analytics_p_timesta_822a76_idx'),
        ),
    ]
