# Generated by Django 5.0.6 on 2026-05-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_score',
            field=models.IntegerField(default=50),
        ),
    ]
